name: Build Docker

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          REGISTRY: cupiddb
          REPOSITORY: cupiddb
        run: |
          echo ${{ steps.buildx.outputs.platforms }}

          docker buildx build \
            --push \
            --target runner \
            --platform ${{ steps.buildx.outputs.platforms }} \
            -t $REGISTRY/$REPOSITORY:${GITHUB_REF##*/} .
